# Generated by Django 6.1 on 2026-08-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drafts",
            fields=[
                ("draft_id", models.TextField(primary_key=True, serialize=False)),
                ("league_id", models.TextField()),
                ("season", models.TextField()),
                ("type", models.TextField()),
                ("status", models.TextField()),
                ("rounds", models.IntegerField()),
                ("slots", models.IntegerField()),
                ("draft_order", models.TextField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "drafts",
            },
        ),
        migrations.CreateModel(
            name="Leagues",
            fields=[
                ("league_id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("season", models.TextField()),
                ("status", models.TextField()),
                ("total_rosters", models.IntegerField()),
                ("draft_id", models.TextField(blank=True, null=True)),
                ("roster_positions", models.TextField(blank=True, null=True)),
                ("scoring_settings", models.TextField(blank=True, null=True)),
                ("settings", models.TextField(blank=True, null=True)),
                ("previous_league_id", models.TextField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "leagues",
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id",
                        "league_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.TextField()),
                ("league_id", models.TextField()),
                ("display_name", models.TextField()),
                ("avatar", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="DraftPicks",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "draft_id",
                        "round",
                        "pick",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("draft_id", models.TextField()),
                ("round", models.IntegerField()),
                ("pick", models.IntegerField()),
                ("roster_id", models.IntegerField()),
                ("player_id", models.TextField(blank=True, null=True)),
                ("picked_by", models.TextField(blank=True, null=True)),
                ("is_keeper", models.IntegerField(blank=True, null=True)),
                ("metadata", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "draft_picks",
                "indexes": [
                    models.Index(fields=["player_id"], name="idx_draft_picks_player"),
                    models.Index(fields=["picked_by"], name="idx_draft_picks_user"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Players",
            fields=[
                ("player_id", models.TextField(primary_key=True, serialize=False)),
                ("full_name", models.TextField(blank=True, null=True)),
                ("position", models.TextField(blank=True, null=True)),
                ("team", models.TextField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("injury_status", models.TextField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "players",
                "indexes": [
                    models.Index(
                        fields=["position", "team"], name="idx_players_pos_team"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                ("transaction_id", models.TextField(primary_key=True, serialize=False)),
                ("league_id", models.TextField()),
                ("type", models.TextField()),
                ("status", models.TextField()),
                ("created_at", models.IntegerField()),
                ("leg", models.IntegerField(blank=True, null=True)),
                ("creator", models.TextField(blank=True, null=True)),
                ("waiver_bid", models.IntegerField(blank=True, null=True)),
                ("adds", models.TextField(blank=True, null=True)),
                ("drops", models.TextField(blank=True, null=True)),
                ("draft_picks", models.TextField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "transactions",
                "indexes": [
                    models.Index(
                        fields=["league_id", "type"],
                        name="idx_transactions_league_type",
                    )
                ],
            },
        ),
    ]
