# Generated by Django 6.1 on 2026-08-18 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.TextField()),
                ("headline", models.TextField()),
                ("body", models.TextField(blank=True, null=True)),
                ("url", models.TextField(unique=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        db_column="player_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="football.players",
                    ),
                ),
            ],
            options={
                "db_table": "news",
                "indexes": [
                    models.Index(
                        fields=["player", "published_at"], name="idx_news_player_date"
                    )
                ],
            },
        ),
    ]
